<?php
/**
 * EnvironmentCopyScope
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permit.io API
 *
 * Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EnvironmentCopyScope Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EnvironmentCopyScope implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EnvironmentCopyScope';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'resources' => '\OpenAPI\Client\Model\EnvironmentCopyScopeFilters',
        'roles' => '\OpenAPI\Client\Model\EnvironmentCopyScopeFilters',
        'user_sets' => '\OpenAPI\Client\Model\EnvironmentCopyScopeFilters',
        'resource_sets' => '\OpenAPI\Client\Model\EnvironmentCopyScopeFilters',
        'custom_policies' => '\OpenAPI\Client\Model\EnvironmentCopyScopeFilters'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'resources' => null,
        'roles' => null,
        'user_sets' => null,
        'resource_sets' => null,
        'custom_policies' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'resources' => false,
        'roles' => false,
        'user_sets' => false,
        'resource_sets' => false,
        'custom_policies' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'resources' => 'resources',
        'roles' => 'roles',
        'user_sets' => 'user_sets',
        'resource_sets' => 'resource_sets',
        'custom_policies' => 'custom_policies'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'resources' => 'setResources',
        'roles' => 'setRoles',
        'user_sets' => 'setUserSets',
        'resource_sets' => 'setResourceSets',
        'custom_policies' => 'setCustomPolicies'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'resources' => 'getResources',
        'roles' => 'getRoles',
        'user_sets' => 'getUserSets',
        'resource_sets' => 'getResourceSets',
        'custom_policies' => 'getCustomPolicies'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('resources', $data ?? [], null);
        $this->setIfExists('roles', $data ?? [], null);
        $this->setIfExists('user_sets', $data ?? [], null);
        $this->setIfExists('resource_sets', $data ?? [], null);
        $this->setIfExists('custom_policies', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets resources
     *
     * @return \OpenAPI\Client\Model\EnvironmentCopyScopeFilters|null
     */
    public function getResources()
    {
        return $this->container['resources'];
    }

    /**
     * Sets resources
     *
     * @param \OpenAPI\Client\Model\EnvironmentCopyScopeFilters|null $resources Resources to copy
     *
     * @return self
     */
    public function setResources($resources)
    {
        if (is_null($resources)) {
            throw new \InvalidArgumentException('non-nullable resources cannot be null');
        }
        $this->container['resources'] = $resources;

        return $this;
    }

    /**
     * Gets roles
     *
     * @return \OpenAPI\Client\Model\EnvironmentCopyScopeFilters|null
     */
    public function getRoles()
    {
        return $this->container['roles'];
    }

    /**
     * Sets roles
     *
     * @param \OpenAPI\Client\Model\EnvironmentCopyScopeFilters|null $roles Roles to copy
     *
     * @return self
     */
    public function setRoles($roles)
    {
        if (is_null($roles)) {
            throw new \InvalidArgumentException('non-nullable roles cannot be null');
        }
        $this->container['roles'] = $roles;

        return $this;
    }

    /**
     * Gets user_sets
     *
     * @return \OpenAPI\Client\Model\EnvironmentCopyScopeFilters|null
     */
    public function getUserSets()
    {
        return $this->container['user_sets'];
    }

    /**
     * Sets user_sets
     *
     * @param \OpenAPI\Client\Model\EnvironmentCopyScopeFilters|null $user_sets User sets to copy
     *
     * @return self
     */
    public function setUserSets($user_sets)
    {
        if (is_null($user_sets)) {
            throw new \InvalidArgumentException('non-nullable user_sets cannot be null');
        }
        $this->container['user_sets'] = $user_sets;

        return $this;
    }

    /**
     * Gets resource_sets
     *
     * @return \OpenAPI\Client\Model\EnvironmentCopyScopeFilters|null
     */
    public function getResourceSets()
    {
        return $this->container['resource_sets'];
    }

    /**
     * Sets resource_sets
     *
     * @param \OpenAPI\Client\Model\EnvironmentCopyScopeFilters|null $resource_sets Resource sets to copy
     *
     * @return self
     */
    public function setResourceSets($resource_sets)
    {
        if (is_null($resource_sets)) {
            throw new \InvalidArgumentException('non-nullable resource_sets cannot be null');
        }
        $this->container['resource_sets'] = $resource_sets;

        return $this;
    }

    /**
     * Gets custom_policies
     *
     * @return \OpenAPI\Client\Model\EnvironmentCopyScopeFilters|null
     */
    public function getCustomPolicies()
    {
        return $this->container['custom_policies'];
    }

    /**
     * Sets custom_policies
     *
     * @param \OpenAPI\Client\Model\EnvironmentCopyScopeFilters|null $custom_policies Custom policies to copy
     *
     * @return self
     */
    public function setCustomPolicies($custom_policies)
    {
        if (is_null($custom_policies)) {
            throw new \InvalidArgumentException('non-nullable custom_policies cannot be null');
        }
        $this->container['custom_policies'] = $custom_policies;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


