<?php
/**
 * GroupRead
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Permit.io API
 *
 * Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GroupRead Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GroupRead implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GroupRead';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'assigned_roles' => 'string[]',
        'users' => 'string[]',
        'group_resource_type_key' => 'string',
        'group_instance_key' => 'string',
        'group_tenant' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'assigned_roles' => null,
        'users' => 'uuid',
        'group_resource_type_key' => null,
        'group_instance_key' => null,
        'group_tenant' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'assigned_roles' => false,
        'users' => false,
        'group_resource_type_key' => false,
        'group_instance_key' => false,
        'group_tenant' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'assigned_roles' => 'assigned_roles',
        'users' => 'users',
        'group_resource_type_key' => 'group_resource_type_key',
        'group_instance_key' => 'group_instance_key',
        'group_tenant' => 'group_tenant'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'assigned_roles' => 'setAssignedRoles',
        'users' => 'setUsers',
        'group_resource_type_key' => 'setGroupResourceTypeKey',
        'group_instance_key' => 'setGroupInstanceKey',
        'group_tenant' => 'setGroupTenant'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'assigned_roles' => 'getAssignedRoles',
        'users' => 'getUsers',
        'group_resource_type_key' => 'getGroupResourceTypeKey',
        'group_instance_key' => 'getGroupInstanceKey',
        'group_tenant' => 'getGroupTenant'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('assigned_roles', $data ?? [], null);
        $this->setIfExists('users', $data ?? [], null);
        $this->setIfExists('group_resource_type_key', $data ?? [], 'group');
        $this->setIfExists('group_instance_key', $data ?? [], null);
        $this->setIfExists('group_tenant', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['group_instance_key'] === null) {
            $invalidProperties[] = "'group_instance_key' can't be null";
        }
        if ($this->container['group_tenant'] === null) {
            $invalidProperties[] = "'group_tenant' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets assigned_roles
     *
     * @return string[]|null
     */
    public function getAssignedRoles()
    {
        return $this->container['assigned_roles'];
    }

    /**
     * Sets assigned_roles
     *
     * @param string[]|null $assigned_roles List of roles that are assigned to this group
     *
     * @return self
     */
    public function setAssignedRoles($assigned_roles)
    {
        if (is_null($assigned_roles)) {
            throw new \InvalidArgumentException('non-nullable assigned_roles cannot be null');
        }
        $this->container['assigned_roles'] = $assigned_roles;

        return $this;
    }

    /**
     * Gets users
     *
     * @return string[]|null
     */
    public function getUsers()
    {
        return $this->container['users'];
    }

    /**
     * Sets users
     *
     * @param string[]|null $users List of user ids that are assigned to this group
     *
     * @return self
     */
    public function setUsers($users)
    {
        if (is_null($users)) {
            throw new \InvalidArgumentException('non-nullable users cannot be null');
        }
        $this->container['users'] = $users;

        return $this;
    }

    /**
     * Gets group_resource_type_key
     *
     * @return string|null
     */
    public function getGroupResourceTypeKey()
    {
        return $this->container['group_resource_type_key'];
    }

    /**
     * Sets group_resource_type_key
     *
     * @param string|null $group_resource_type_key The key of the resource type that the group belongs to.
     *
     * @return self
     */
    public function setGroupResourceTypeKey($group_resource_type_key)
    {
        if (is_null($group_resource_type_key)) {
            throw new \InvalidArgumentException('non-nullable group_resource_type_key cannot be null');
        }
        $this->container['group_resource_type_key'] = $group_resource_type_key;

        return $this;
    }

    /**
     * Gets group_instance_key
     *
     * @return string
     */
    public function getGroupInstanceKey()
    {
        return $this->container['group_instance_key'];
    }

    /**
     * Sets group_instance_key
     *
     * @param string $group_instance_key The key of the resource instance that the group belongs to.
     *
     * @return self
     */
    public function setGroupInstanceKey($group_instance_key)
    {
        if (is_null($group_instance_key)) {
            throw new \InvalidArgumentException('non-nullable group_instance_key cannot be null');
        }
        $this->container['group_instance_key'] = $group_instance_key;

        return $this;
    }

    /**
     * Gets group_tenant
     *
     * @return string
     */
    public function getGroupTenant()
    {
        return $this->container['group_tenant'];
    }

    /**
     * Sets group_tenant
     *
     * @param string $group_tenant The tenant key or id that the group belongs to.
     *
     * @return self
     */
    public function setGroupTenant($group_tenant)
    {
        if (is_null($group_tenant)) {
            throw new \InvalidArgumentException('non-nullable group_tenant cannot be null');
        }
        $this->container['group_tenant'] = $group_tenant;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


